version: "3"

services:
  dailydnode0:
    container_name: dailydnode0
    image: "dailyd/node"
    ports:
      - "26657:26657"
      - "8545:8545"
      - "8546:8546"
      - "8125:8125"
    environment:
      - ID=0
      - LOG=${LOG:-dailyd.log}
    volumes:
      - ./localnet-setup/node0/dailyd:/ethermint:Z
    networks:
      - localnet
    entrypoint: "bash start-docker.sh"

  dailydnode1:
    container_name: dailydnode1
    image: "dailyd/node"
    ports:
      - "26658:26657"
      - "8555:8545"
      - "8556:8546"
      - "8126:8125"
    environment:
      - ID=1
      - LOG=${LOG:-dailyd.log}
    volumes:
      - ./localnet-setup/node1/dailyd:/ethermint:Z
    networks:
      - localnet
    entrypoint: "bash start-docker.sh"

  dailydnode2:
    container_name: dailydnode2
    image: "dailyd/node"
    environment:
      - ID=2
      - LOG=${LOG:-dailyd.log}
    ports:
      - "26659:26657"
      - "8565:8545"
      - "8566:8546"
      - "8127:8125"
    volumes:
      - ./localnet-setup/node2/dailyd:/ethermint:Z
    networks:
      - localnet
    entrypoint: "bash start-docker.sh"

  dailydnode3:
    container_name: dailydnode3
    image: "dailyd/node"
    environment:
      - ID=3
      - LOG=${LOG:-dailyd.log}
    ports:
      - "26660:26657"
      - "8575:8545"
      - "8576:8546"
      - "8128:8125"
    volumes:
      - ./localnet-setup/node3/dailyd:/ethermint:Z
    networks:
      - localnet
    entrypoint: "bash start-docker.sh"

networks:
  localnet:
